[workspace]
exclude = [
    "language/compilers",
    "tools/ide-plugins"
]
members = [
    "language/*",
    "language/compilers/*",
    "tools/*",
    "tools/magpie/magpie-lib",
    "tools/magpie/magpie-wrapper",
    "tools/ide-plugins/raven-language-server"
]
resolver = "2"